// Static mock data for the wireframe. No backend.
import type { Order, Truck, User } from "./types"

export const ME_SHIPPER: User = {
  id: "u-me-shipper",
  name: "Айдос Сериков",
  phone: "+7 701 555 12 34",
  rating: 4.8,
  dealsCount: 37,
  role: "shipper",
  company: "ИП Сериков",
}

export const ME_CARRIER: User = {
  id: "u-me-carrier",
  name: "Бауыржан Нур",
  phone: "+7 705 333 88 11",
  rating: 4.9,
  dealsCount: 124,
  role: "carrier",
}

export const MY_FLEET: Truck[] = [
  { id: "t1", type: "тент", maxWeightKg: 20000, maxVolumeM3: 86, plate: "777 ABC 02" },
  { id: "t2", type: "рефрижератор", maxWeightKg: 18000, maxVolumeM3: 80, plate: "012 KZA 05" },
]

export const WATCHED_ROUTES = ["Хоргос → Алматы", "Хоргос → Астана"]

const carriers: User[] = [
  { id: "c1", name: "Бауыржан Нур", phone: "+7 705 333 88 11", rating: 4.9, dealsCount: 124, role: "carrier" },
  { id: "c2", name: "Ерлан Қасым", phone: "+7 707 121 45 67", rating: 4.6, dealsCount: 58, role: "carrier" },
  { id: "c3", name: "Дамир Тлеу", phone: "+7 700 909 10 20", rating: 4.3, dealsCount: 22, role: "carrier" },
]

const shippers: User[] = [
  { id: "s1", name: "Айдос Сериков", phone: "+7 701 555 12 34", rating: 4.8, dealsCount: 37, role: "shipper", company: "ИП Сериков" },
  { id: "s2", name: "Гүлнар Омарова", phone: "+7 702 444 77 88", rating: 4.7, dealsCount: 19, role: "shipper" },
  { id: "s3", name: "Triple-A Logistics", phone: "+7 727 312 00 00", rating: 4.5, dealsCount: 210, role: "shipper", company: "ТОО Triple-A" },
]

// Orders authored by ME_SHIPPER — drives the "Мои заказы" screen.
export const MY_ORDERS: Order[] = [
  {
    id: "ord-1001",
    origin: "Хоргос",
    destination: "Алматы",
    cargo: "Электроника (смартфоны, аксессуары), 18 паллет",
    weightKg: 4200,
    volumeM3: 24,
    truckType: "тент",
    priceUsd: 1450,
    readyDate: "08 июн 2026",
    status: "bidding",
    shipper: ME_SHIPPER,
    address: "Алматы, ул. Райымбека 348, склад 5",
    recipientName: "Нуржан",
    recipientPhone: "+7 701 200 30 40",
    payment: "transfer",
    createdAgo: "2 ч назад",
    offers: [
      { id: "of-1", carrier: carriers[0], truck: "тент", kind: "accept", priceUsd: 1450, status: "pending", createdAgo: "40 мин назад" },
      { id: "of-2", carrier: carriers[1], truck: "тент", kind: "counter", priceUsd: 1600, status: "pending", createdAgo: "25 мин назад" },
      { id: "of-3", carrier: carriers[2], truck: "тент", kind: "counter", priceUsd: 1550, status: "pending", createdAgo: "12 мин назад" },
    ],
  },
  {
    id: "ord-1002",
    origin: "Хоргос",
    destination: "Астана",
    cargo: "Бытовая техника, 30 коробок",
    weightKg: 9800,
    volumeM3: 52,
    truckType: "рефрижератор",
    priceUsd: 2300,
    readyDate: "10 июн 2026",
    status: "deal",
    shipper: ME_SHIPPER,
    address: "Астана, пр. Кабанбай батыра 12",
    recipientName: "Сауле",
    recipientPhone: "+7 702 777 99 00",
    payment: "cash",
    createdAgo: "1 дн назад",
    offers: [],
    deal: {
      status: "in_transit",
      carrier: carriers[0],
      agreedPriceUsd: 2300,
      chat: [
        { id: "m1", fromMe: false, text: "Здравствуйте, груз забрал, выезжаю из Хоргоса.", time: "09:12" },
        { id: "m2", fromMe: true, text: "Отлично, держите в курсе на границе 🙏", time: "09:15" },
        { id: "m3", fromMe: false, text: "Принято. Ориентир — граница к вечеру.", time: "09:16" },
      ],
    },
  },
  {
    id: "ord-1003",
    origin: "Хоргос",
    destination: "Шымкент",
    cargo: "Текстиль, рулоны ткани",
    weightKg: 6100,
    volumeM3: 40,
    truckType: "тент",
    priceUsd: 1700,
    readyDate: "05 июн 2026",
    status: "archived",
    shipper: ME_SHIPPER,
    address: "Шымкент, рынок Самал, контейнер 220",
    recipientName: "Ержан",
    recipientPhone: "+7 705 111 22 33",
    payment: "cash",
    createdAgo: "4 дн назад",
    offers: [],
  },
  {
    id: "ord-1004",
    origin: "Хоргос",
    destination: "Алматы",
    cargo: "Запчасти для авто",
    weightKg: 2500,
    volumeM3: 14,
    truckType: "бортовой",
    priceUsd: 900,
    readyDate: "12 июн 2026",
    status: "published",
    shipper: ME_SHIPPER,
    address: "Алматы, ул. Толе би 280",
    recipientName: "Марат",
    recipientPhone: "+7 707 808 90 10",
    payment: "transfer",
    createdAgo: "20 мин назад",
    offers: [],
  },
]

// Public feed for carriers — orders from various shippers.
export const FEED_ORDERS: Order[] = [
  {
    id: "ord-2001",
    origin: "Хоргос",
    destination: "Алматы",
    cargo: "Электроника (смартфоны, аксессуары), 18 паллет",
    weightKg: 4200,
    volumeM3: 24,
    truckType: "тент",
    priceUsd: 1450,
    readyDate: "08 июн 2026",
    status: "bidding",
    shipper: shippers[0],
    address: "Алматы, ул. Райымбека 348",
    recipientName: "Нуржан",
    recipientPhone: "+7 701 200 30 40",
    payment: "transfer",
    createdAgo: "2 ч назад",
    offers: [],
    myOfferStatus: "pending",
  },
  {
    id: "ord-2002",
    origin: "Хоргос",
    pickupPoint: "Хоргос, МЦПС, склад В-4",
    pickupPhone: "+7 705 880 11 22",
    destination: "Астана",
    cargo: "Стройматериалы, плитка",
    weightKg: 15000,
    volumeM3: 60,
    truckType: "тент",
    priceUsd: 2600,
    readyDate: "09 июн 2026",
    status: "published",
    shipper: shippers[2],
    address: "Астана, ул. Сыганак 18",
    recipientName: "Олжас",
    recipientPhone: "+7 717 222 33 44",
    payment: "transfer",
    createdAgo: "35 мин назад",
    offers: [],
  },
  {
    id: "ord-2003",
    origin: "Хоргос",
    pickupPoint: "Хоргос, сухой порт, терминал 2",
    pickupPhone: "+86 138 0000 1122",
    destination: "Шымкент",
    cargo: "Продукты питания (сухие), 22 паллеты",
    weightKg: 8700,
    volumeM3: 48,
    truckType: "рефрижератор",
    priceUsd: 1980,
    readyDate: "07 июн 2026",
    notes: "Нужна растаможка на границе. Хрупкое — аккуратная погрузка.",
    status: "published",
    shipper: shippers[1],
    address: "Шымкент, ул. Байтурсынова 5",
    recipientName: "Асель",
    recipientPhone: "+7 705 600 70 80",
    payment: "cash",
    createdAgo: "1 ч назад",
    offers: [],
  },
  {
    id: "ord-2004",
    origin: "Хоргос",
    destination: "Караганда",
    cargo: "Мебель в разборе",
    weightKg: 5400,
    volumeM3: 70,
    truckType: "тент",
    priceUsd: 2100,
    readyDate: "11 июн 2026",
    status: "published",
    shipper: shippers[2],
    address: "Караганда, пр. Бухар жырау 49",
    recipientName: "Тимур",
    recipientPhone: "+7 721 909 80 70",
    payment: "transfer",
    createdAgo: "3 ч назад",
    offers: [],
  },
  {
    id: "ord-2005",
    origin: "Хоргос",
    destination: "Астана",
    cargo: "Металлопрокат, тяжёлая партия",
    weightKg: 26000,
    volumeM3: 64,
    truckType: "бортовой",
    priceUsd: 3400,
    readyDate: "13 июн 2026",
    status: "published",
    shipper: shippers[2],
    address: "Астана, промзона, склад 7",
    recipientName: "Кайрат",
    recipientPhone: "+7 717 555 10 20",
    payment: "transfer",
    createdAgo: "30 мин назад",
    offers: [],
  },
]
