// Static mock data for the wireframe. No backend.
import type { Order, Truck, User } from "./types"

export const ME_SHIPPER: User = {
  id: "u-me-shipper",
  name: "Айдос Сериков",
  phone: "+7 701 555 12 34",
  rating: 4.8,
  dealsCount: 37,
  role: "shipper",
  company: "ИП Сериков",
}

export const ME_CARRIER: User = {
  id: "u-me-carrier",
  name: "Бауыржан Нур",
  phone: "+7 705 333 88 11",
  rating: 4.9,
  dealsCount: 124,
  role: "carrier",
}

export const MY_FLEET: Truck[] = [
  { id: "t1", type: "тент", maxWeightKg: 20000, maxVolumeM3: 86, plate: "777 ABC 02" },
  { id: "t2", type: "рефрижератор", maxWeightKg: 18000, maxVolumeM3: 80, plate: "012 KZA 05" },
]

export const WATCHED_ROUTES = ["Алматы → Москва", "Астана → Новосибирск", "Ташкент → Алматы"]

export const carriers: User[] = [
  {
    id: "c1", name: "Бауыржан Нур", phone: "+7 705 333 88 11", rating: 4.9, dealsCount: 124,
    role: "carrier", verified: true, onTimeRate: 97, memberSince: "2023",
    trucks: [
      { id: "c1t1", type: "тент", maxWeightKg: 20000, maxVolumeM3: 86, plate: "777 ABC 02" },
      { id: "c1t2", type: "рефрижератор", maxWeightKg: 18000, maxVolumeM3: 80, plate: "012 KZA 05" },
    ],
    reviews: [
      { id: "rv1", author: "Айдос С.", rating: 5, text: "Довёз вовремя, аккуратно. Рекомендую.", ago: "2 нед назад" },
      { id: "rv2", author: "Гүлнар О.", rating: 5, text: "Хорошая связь на всём пути.", ago: "1 мес назад" },
      { id: "rv3", author: "Triple-A", rating: 4, text: "Всё ок, чуть задержался на границе.", ago: "1 мес назад" },
    ],
  },
  {
    id: "c2", name: "Ерлан Қасым", phone: "+7 707 121 45 67", rating: 4.6, dealsCount: 58,
    role: "carrier", verified: true, onTimeRate: 91, memberSince: "2024",
    trucks: [{ id: "c2t1", type: "тент", maxWeightKg: 22000, maxVolumeM3: 90, plate: "555 KZB 09" }],
    reviews: [
      { id: "rv4", author: "Айдос С.", rating: 5, text: "Быстро откликнулся, честная цена.", ago: "3 нед назад" },
      { id: "rv5", author: "Сауле К.", rating: 4, text: "Нормально, но опоздал на погрузку.", ago: "2 мес назад" },
    ],
  },
  {
    id: "c3", name: "Дамир Тлеу", phone: "+7 700 909 10 20", rating: 4.3, dealsCount: 22,
    role: "carrier", verified: false, onTimeRate: 85, memberSince: "2025",
    trucks: [{ id: "c3t1", type: "тент", maxWeightKg: 20000, maxVolumeM3: 82, plate: "108 KZC 11" }],
    reviews: [{ id: "rv6", author: "Марат Е.", rating: 4, text: "Груз доставил, связь могла быть лучше.", ago: "1 мес назад" }],
  },
]

const shippers: User[] = [
  { id: "s1", name: "Айдос Сериков", phone: "+7 701 555 12 34", rating: 4.8, dealsCount: 37, role: "shipper", company: "ИП Сериков" },
  { id: "s2", name: "Гүлнар Омарова", phone: "+7 702 444 77 88", rating: 4.7, dealsCount: 19, role: "shipper" },
  { id: "s3", name: "Triple-A Logistics", phone: "+7 727 312 00 00", rating: 4.5, dealsCount: 210, role: "shipper", company: "ТОО Triple-A" },
]

// Orders authored by ME_SHIPPER — drives the "Мои заказы" screen.
export const MY_ORDERS: Order[] = [
  {
    id: "ord-1001",
    origin: "Караганда",
    destination: "Алматы",
    cargo: "Электроника (смартфоны, аксессуары), 18 паллет",
    weightKg: 4200,
    volumeM3: 24,
    truckType: "тент",
    priceUsd: 1450,
    readyDate: "08 июн 2026",
    status: "bidding",
    shipper: ME_SHIPPER,
    address: "Алматы, ул. Райымбека 348, склад 5",
    recipientName: "Нуржан",
    recipientPhone: "+7 701 200 30 40",
    payment: "transfer",
    createdAgo: "2 ч назад",
    offers: [
      { id: "of-1", carrier: carriers[0], truck: "тент", plate: "777 ABC 02", capacityKg: 20000, kind: "accept", priceUsd: 1450, status: "pending", createdAgo: "40 мин назад" },
      { id: "of-2", carrier: carriers[1], truck: "тент", plate: "555 KZB 09", capacityKg: 22000, kind: "counter", priceUsd: 1600, status: "pending", createdAgo: "25 мин назад" },
      { id: "of-3", carrier: carriers[2], truck: "тент", plate: "108 KZC 11", capacityKg: 20000, kind: "counter", priceUsd: 1550, status: "pending", createdAgo: "12 мин назад" },
    ],
  },
  {
    id: "ord-1002",
    origin: "Москва",
    destination: "Астана",
    cargo: "Бытовая техника, 30 коробок",
    weightKg: 9800,
    volumeM3: 52,
    truckType: "рефрижератор",
    priceUsd: 2300,
    readyDate: "10 июн 2026",
    deliverBy: "14 июн 2026",
    overdue: true,
    status: "deal",
    shipper: ME_SHIPPER,
    address: "Астана, пр. Кабанбай батыра 12",
    recipientName: "Сауле",
    recipientPhone: "+7 702 777 99 00",
    payment: "cash",
    createdAgo: "1 дн назад",
    offers: [],
    deal: {
      status: "accepted",
      carrier: carriers[0],
      agreedPriceUsd: 2300,
      chat: [
        { id: "m1", fromMe: false, text: "Здравствуйте, груз забрал, выезжаю из Хоргоса.", time: "09:12" },
        { id: "m2", fromMe: true, text: "Отлично, держите в курсе на границе 🙏", time: "09:15" },
        { id: "m3", fromMe: false, text: "Принято. Ориентир — граница к вечеру.", time: "09:16" },
      ],
    },
  },
  {
    id: "ord-1003",
    origin: "Ташкент",
    destination: "Шымкент",
    cargo: "Текстиль, рулоны ткани",
    weightKg: 6100,
    volumeM3: 40,
    truckType: "тент",
    priceUsd: 1700,
    readyDate: "05 июн 2026",
    status: "archived",
    shipper: ME_SHIPPER,
    address: "Шымкент, рынок Самал, контейнер 220",
    recipientName: "Ержан",
    recipientPhone: "+7 705 111 22 33",
    payment: "cash",
    createdAgo: "4 дн назад",
    offers: [],
  },
  {
    id: "ord-1004",
    origin: "Астана",
    destination: "Алматы",
    cargo: "Запчасти для авто",
    weightKg: 2500,
    volumeM3: 14,
    truckType: "бортовой",
    priceUsd: 900,
    readyDate: "12 июн 2026",
    status: "published",
    shipper: ME_SHIPPER,
    address: "Алматы, ул. Толе би 280",
    recipientName: "Марат",
    recipientPhone: "+7 707 808 90 10",
    payment: "transfer",
    createdAgo: "20 мин назад",
    offers: [],
  },
  // Завершённые заказы — история для аналитики.
  {
    id: "ord-0990", origin: "Бишкек", destination: "Алматы", cargo: "Одежда, 20 коробок",
    weightKg: 3800, volumeM3: 22, truckType: "тент", priceUsd: 1300, readyDate: "20 май 2026",
    status: "deal", shipper: ME_SHIPPER, address: "Алматы, ул. Абая 10", recipientName: "Ержан",
    recipientPhone: "+7 701 111 22 33", payment: "transfer", createdAgo: "3 нед назад",
    completedAt: "Май", offers: [],
    deal: { status: "completed", carrier: carriers[0], agreedPriceUsd: 1300, chat: [] },
  },
  {
    id: "ord-0985", origin: "Хоргос", destination: "Астана", cargo: "Электроника, 14 паллет",
    weightKg: 7600, volumeM3: 40, truckType: "рефрижератор", priceUsd: 2200, readyDate: "12 май 2026",
    status: "deal", shipper: ME_SHIPPER, address: "Астана, пр. Туран 5", recipientName: "Аружан",
    recipientPhone: "+7 702 333 44 55", payment: "cash", createdAgo: "1 мес назад",
    completedAt: "Май", offers: [],
    deal: { status: "completed", carrier: carriers[1], agreedPriceUsd: 2200, chat: [] },
  },
  {
    id: "ord-0980", origin: "Шымкент", destination: "Алматы", cargo: "Косметика, 30 коробок",
    weightKg: 4100, volumeM3: 26, truckType: "тент", priceUsd: 1400, readyDate: "28 апр 2026",
    status: "deal", shipper: ME_SHIPPER, address: "Алматы, ул. Сатпаева 5", recipientName: "Дана",
    recipientPhone: "+7 705 777 88 99", payment: "transfer", createdAgo: "2 мес назад",
    completedAt: "Апрель", offers: [],
    deal: { status: "completed", carrier: carriers[0], agreedPriceUsd: 1400, chat: [] },
  },
]

// Public feed for carriers — orders from various shippers.
export const FEED_ORDERS: Order[] = [
  {
    id: "ord-2001",
    origin: "Караганда",
    destination: "Алматы",
    cargo: "Электроника (смартфоны, аксессуары), 18 паллет",
    weightKg: 4200,
    volumeM3: 24,
    truckType: "тент",
    priceUsd: 1450,
    readyDate: "08 июн 2026",
    status: "bidding",
    shipper: shippers[0],
    address: "Алматы, ул. Райымбека 348",
    recipientName: "Нуржан",
    recipientPhone: "+7 701 200 30 40",
    payment: "transfer",
    createdAgo: "2 ч назад",
    offers: [],
    myOfferStatus: "pending",
  },
  {
    id: "ord-2002",
    origin: "Новосибирск",
    pickupPoint: "Терминал МЦПС, склад В-4",
    pickupPhone: "+7 705 880 11 22",
    destination: "Астана",
    cargo: "Стройматериалы, плитка",
    weightKg: 15000,
    volumeM3: 60,
    truckType: "тент",
    priceUsd: 2600,
    readyDate: "09 июн 2026",
    status: "published",
    shipper: shippers[2],
    address: "Астана, ул. Сыганак 18",
    recipientName: "Олжас",
    recipientPhone: "+7 717 222 33 44",
    payment: "transfer",
    createdAgo: "35 мин назад",
    offers: [],
  },
  {
    id: "ord-2003",
    origin: "Алматы",
    pickupPoint: "Сухой порт, терминал 2",
    pickupPhone: "+86 138 0000 1122",
    destination: "Шымкент",
    cargo: "Продукты питания (сухие), 22 паллеты",
    weightKg: 8700,
    volumeM3: 48,
    truckType: "рефрижератор",
    priceUsd: 1980,
    readyDate: "07 июн 2026",
    notes: "Нужна растаможка на границе. Хрупкое — аккуратная погрузка.",
    status: "published",
    shipper: shippers[1],
    address: "Шымкент, ул. Байтурсынова 5",
    recipientName: "Асель",
    recipientPhone: "+7 705 600 70 80",
    payment: "cash",
    createdAgo: "1 ч назад",
    offers: [],
  },
  {
    id: "ord-2004",
    origin: "Москва",
    destination: "Караганда",
    cargo: "Мебель в разборе",
    weightKg: 5400,
    volumeM3: 70,
    truckType: "тент",
    priceUsd: 2100,
    readyDate: "11 июн 2026",
    status: "published",
    shipper: shippers[2],
    address: "Караганда, пр. Бухар жырау 49",
    recipientName: "Тимур",
    recipientPhone: "+7 721 909 80 70",
    payment: "transfer",
    createdAgo: "3 ч назад",
    offers: [],
  },
  {
    id: "ord-2005",
    origin: "Ташкент",
    destination: "Астана",
    cargo: "Металлопрокат, тяжёлая партия",
    weightKg: 26000,
    volumeM3: 64,
    truckType: "бортовой",
    priceUsd: 3400,
    readyDate: "13 июн 2026",
    status: "published",
    shipper: shippers[2],
    address: "Астана, промзона, склад 7",
    recipientName: "Кайрат",
    recipientPhone: "+7 717 555 10 20",
    payment: "transfer",
    createdAgo: "30 мин назад",
    offers: [],
  },
  // Выигранные перевозчиком грузы → его вкладка «Сделки».
  {
    id: "ord-2006",
    origin: "Астана",
    destination: "Алматы",
    cargo: "Бытовая техника, 26 коробок",
    weightKg: 8600,
    volumeM3: 50,
    truckType: "тент",
    priceUsd: 1850,
    readyDate: "06 июн 2026",
    status: "deal",
    shipper: shippers[0],
    address: "Алматы, ул. Сатпаева 90",
    recipientName: "Данияр",
    recipientPhone: "+7 701 303 40 50",
    payment: "transfer",
    createdAgo: "вчера",
    offers: [],
    myOfferStatus: "accepted",
    myOfferPriceUsd: 1850,
    deal: {
      status: "accepted",
      carrier: ME_CARRIER,
      agreedPriceUsd: 1850,
      chat: [
        { id: "cm1", fromMe: false, text: "Здравствуйте! Когда сможете забрать груз?", time: "08:40" },
        { id: "cm2", fromMe: true, text: "Уже на складе, гружусь. Выезжаю через час.", time: "08:52" },
      ],
    },
  },
  {
    id: "ord-2007",
    origin: "Бишкек",
    destination: "Шымкент",
    cargo: "Обувь, 15 паллет",
    weightKg: 5200,
    volumeM3: 36,
    truckType: "тент",
    priceUsd: 1400,
    readyDate: "01 июн 2026",
    status: "deal",
    shipper: shippers[1],
    address: "Шымкент, ул. Кунаева 12",
    recipientName: "Аружан",
    recipientPhone: "+7 705 909 10 11",
    payment: "cash",
    createdAgo: "3 дн назад",
    offers: [],
    myOfferStatus: "accepted",
    myOfferPriceUsd: 1400,
    deal: {
      status: "completed",
      carrier: ME_CARRIER,
      agreedPriceUsd: 1400,
      chat: [],
    },
  },
]
